---
title: "Get started with fwebinfr"
author: "Kevin Cazelles"
date: 04-04-2024
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started with fwebinfr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The goal of the package `fwebinfr` is to predict interaction strengths in food web models by solving Linear Inverse Models (LIM). `fwebinfr` provides a user-friendly interface to create such problems and leverages [`limSolve`](https://CRAN.R-project.org/package=limSolve) behind the scenes to solve them.


# Basic 2 species system

Here is a built-in example with 2 species. First, we load the package along with packages to create plots.

```{R setup}
library(fwebinfr)
library(ggplot2)
library(patchwork)
```

This example is available in the package and is called using `fw_example_2species()`.

```{R value}
# a first example
net <- fw_example_2species()
net
```

It is an object of class `fw_model` that includes all details needed for the inference. For the sake of the example, matrix A contains the real interactions, and by default, none will be used for the inference as there are interpreted as unknown according to matrix `U`. A quick visualization of the dynamics. 

```{R plot}
fw_ode_plot(net, rep(0.3, 2), seq(1, 500, 0.1))
```


# Inferring interaction strengths

We now call `fw_infer()` which requires an object of class `fw_problem` that is here obtained by calling `fw_as_problem()`.

```{R compute}
res <- fw_as_problem(net) |> fw_infer()
class(res)
dim(res$prediction)
head(res$prediction)
```

Note that we can also use extra parameters of the `limSolve::xsample()`, which is ultimately called.

```{R compute2}
res <- fw_infer(fw_as_problem(net), burninlength = 5000, iter = 5000, type = "mirror")
class(res)
```

<!--  WORKSHOP STUFF -->
```R
res <- fw_infer(fw_as_problem(net), burninlength = 5000, iter = 5000, type = "mirror") 
    
fw_range_plot(res, show_points = FALSE, show_lev = FALSE) + 
  ggtitle("") +
  xlab("") +
  theme(text = element_text(size = 16))
ggsave("distrib_2sp.png", width = 10, height = 8)

fw_range_plot(res, show_points = TRUE, show_lev = FALSE) +
  ggtitle("") +
  xlab("") +
  theme(text = element_text(size = 16))
ggsave("distrib_2sp_points.png", width = 10, height = 8)


fw_range_plot(res, show_points = FALSE, show_lev = TRUE) +
  ylab("")
ggsave("distrib_2sp_stab.png", width = 9, height = 7)

fw_range_plot(res, show_points = FALSE, show_lev = TRUE, inv = TRUE) +
  ggtitle("Resilience") + 
  ylab("")
ggsave("distrib_2sp_stab_res.png", width = 9, height = 7)

```

Here, `burninlength` = 5000, `iter` and `type` are actually parameters passed to `limSolve::xsample()`. The output is an object of class `fw_predicted` which is a list of two elements: 
  1. `prediction` a data frame of the prediction,
  2. `problem` the original problem.
  
```{R pred}
dim(res$prediction)
head(res$prediction)
```

There are functions to quickly explore the results. For the range of interaction strengths can be used visualize with `fw_range_plot()`.

```{R res}
fw_range_plot(res)
```

This function also allows one to see the individual points coloured according to their stability.

```{R range2}
fw_range_plot(res, show_points = TRUE)
```

There is also an option to compare the most stable set of parameters to the rest of value. By default, it compares the 25% most stable systems to the rest of the systems. 

```{R range3}
fw_range_compare_plot(res)
```

For any result, we can check the food web predicted:

```{R predictA}
fw_predict_A(res, 1)
fw_predict_A(res, 1000)
```

as well as the biomass (which should equal the one we provided).

```{R predictB}
fw_predict_B(res, 1)
fw_predict_B(res, 1000)
```


## Compare most and least stable systems

Let's plot the dynamics for the system with the min and max leading eigen value.


```{R compare1, fig.height = 10}
# we create one new `fw_problem` object with the most stable system and another one
# with the the leas stable system. 

net_most_stable <- fw_model(
  A = fw_predict_A(res, which.min(res$prediction$leading_ev)),
  B = fw_predict_B(res, which.min(res$prediction$leading_ev)),
  R = net$R
)
net_least_stable <- fw_model(
    A = fw_predict_A(res, which.max(res$prediction$leading_ev)),
    B = fw_predict_B(res, which.max(res$prediction$leading_ev)),
    R = net$R
)

p1 <- fw_ode_plot(net_most_stable, rep(0.3, 2), seq(1, 500, 0.1)) + 
  ggtitle("Minimum leading eigen value (most stable)")
p2 <- fw_ode_plot(net_least_stable, rep(0.3, 2), seq(1, 500, 0.1)) +
  ggtitle("Maximum leading eigen value (least stable)")
p1 / p2

p1 + ggtitle("Most stable")
ggsave("most_stable.png", width = 8, height = 6)
p2 + ggtitle("Least stable")
ggsave("least_stable.png", width = 8, height = 6)
```


## Working with known interactions

In the example above, all non-null interactions are regarded as unknown once the `fw_model` object is passed to `fw_problem`. 
In some cases, part of the interaction may be known. To specify what interactions are known, we define U. For instance let's assume `A[1,1]` is known and equals -0.1.

```{R known_interaction} 
# use the U matrix
U <- res$problem$U
# set the first interaction to known
U$unknown[1] <- FALSE

res2 <- fw_problem(A = net$A, B = net$B, R = net$R, U) |> 
  fw_infer()
res2
```

As mentioned by the warning, there is only one solution here, the one solution we started with.

```{R uique_ol} 
uniq_sys <- fw_model(
  A = fw_predict_A(res2, 1),
  B = fw_predict_B(res2, 1),
  R = net$R
)
fw_ode_plot(uniq_sys, rep(0.3, 2), seq(1, 500, 0.1)) +
   ggtitle("Unique solution")
```