# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name webFromNicheModel
#'
#' @title Core implementation of the niche model.
#'
#' @importFrom Rcpp evalCpp
#'
webFromNicheModel <- function(nsp, connec, niche, connect_all = FALSE, unbias = FALSE) {
    .Call('_fwebinfr_webFromNicheModel', PACKAGE = 'fwebinfr', nsp, connec, niche, connect_all, unbias)
}

